### ISSUE TITLE
Internal server error when trying to Kepubify a bad file

### ISSUE THREAD

**Issue by johanbrook** [daniel-j/send2ereader#21]
Maybe this is https://github.com/daniel-j/send2ereader/issues/6, but:

1. Upload a "bad" file, such as [1].
2. Check "Kepubify".
3. Upload.

A page with "Internal server error" is shown. Unchecking "Kepubify" successfully uploads the file.

I uploaded the EPUB to https://pgaskin.net/kepubify/try (online version of Kepubify) and it fails there, which confirms that the file is bad somehow.

Anyhow, I suggest catching this error and presenting it nicely with suggestion to turn off Kepubify.

Thanks for an otherwise super smooth experience <3

[1] https://archive.org/download/dune-saga-collection/Dune%20Saga%20Collection/Frank%20Herbert/Dune%20%28286%29/Dune%20-%20Frank%20Herbert.epub

**Comment by daniel-j** [comment]
Hey. The epub link you provided no longer works. I looked around and found https://archive.org/download/dune-by-frank-herbert/Dune%20by%20Frank%20Herbert.epub which kepubify successfully converted but the Kobo fails to open, although it doesn't sound like your exact issue.

**Comment by daniel-j** [comment]
I have made the kepubify cli output show in case conversion fails. So this should be resolved.
