### ISSUE TITLE
Cannot download a file with a capitalized extension

### ISSUE THREAD

**Issue by paul-arg** [daniel-j/send2ereader#26]
Hello,

First of all thank you for this amazing tool.

I tried uploading the following file: `file.EPUB`. The file was uploaded correctly and visible on the Kobo, but when I clicked on the download link, nothing happened.

I renamed the file to `file.epub` and it worked correctly.

Sometimes EPUB or PDF files I download from the internet have capitalized extensions so this might occur with other people too.

**Comment by daniel-j** [comment]
Completed in https://github.com/daniel-j/send2ereader/commit/235308f5f38a703fdb03aa879e8c1dbfa251bfa4
