### ISSUE TITLE
Not working with new Tolino Shine Color

### ISSUE THREAD

**Issue by danielkr123** [daniel-j/send2ereader#28]
Hello,
Unfortunately, the service does not seem to work with the new Tolino Shine Color. When opening the URL „https://send.djazz.se“ on the device, it does not recognize being opened on the e-reader and does not display the unique key but then“normal“ uploading page as on any other device.

Device: Tolino Shine Color (= Kobo)
Firmware: 5.0.175773 (latest)

![image](https://github.com/daniel-j/send2ereader/assets/22988970/d19d43ad-9536-42a0-a29a-1e843dc15617)

**Comment by daniel-j** [comment]
Hello! Can you visit https://www.whatismybrowser.com/detect/what-is-my-user-agent/ on your Tolino ereader and report back what the User Agent is? I check it if it contains "Kobo" or "Kindle" but I haven't seen "Tolino" in the request logs.

**Comment by daniel-j** [comment]
I have now added detection for when the User-Agent contains "eReader". Thanks for the feedback! Let me know if it doesn't work and I'll repoen the issue.

**Comment by danielkr123** [comment]
I can confirm that it is working now. Thanks!
