### ISSUE TITLE
Upload Error: Request Entity Too Large

### ISSUE THREAD

**Issue by hassaan22** [daniel-j/send2ereader#4]
Hi!

As of today, I keep getting "Request Entity Too Large" error anytime I try to upload an epub file. I tried files that worked a week ago and they, too, lead to this error, which tells me its not the file itself causing the problem, but something in the backend?

Please let me know if you need any additional info or help. Thank you

<img width="1397" alt="Screen Shot 2021-11-30 at 2 58 53 PM" src="https://user-images.githubusercontent.com/7843417/144141730-ec58654f-c639-4380-ba82-0b8e78fb24ff.png">

**Comment by daniel-j** [comment]
Sorry, I forgot to answer this. I upgraded nginx and it reverted to default settings, for example the max upload file size. Should be working.
