### ISSUE TITLE
State URL on page

### ISSUE THREAD

**Issue by strider72** [daniel-j/send2ereader#9]
I used Nickel Menu to add a modal shortcut to https://send.djazz.se/ to my Kobo device.  Ironically, the site itself doesn't say the URL anywhere, so I forget where I'm supposed to go on the other device.

Simply a sentence on the Kobo end saying something like "Go to https://send.djazz.se/ to send ebooks to this device" would be a nice boost to usability.

**Comment by faaarmer** [comment]
How did you add a shortcut? I've got nickel menu installed but just set this site as my home page on the "experimental" browser

**Comment by daniel-j** [comment]
The url has now been added to the bottom of the page.
